### ISSUE TITLE
booleans not evaluated correctly in _when_ statements 

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/ansible-galaxy-extras#81]
If there is an _and_ operator inside a _when_ statement, then booleans apparently get evaluated as strings. This gets reflected when setting the `galaxy_extras_config_slurm` and `supervisor_manage_slurm` both to false and running with the default `provision.yml` used in bgruening/docker-galaxy-stable:

```ansible
TASK [galaxy-extras : Stop and remove munge.] **********************************
failed: [localhost] (item=munge) => {"failed": true, "item": "munge", "msg": "no service or tool found for: munge"}
	to retry, use: --limit @provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=19   changed=2    unreachable=0    failed=1 
```

This is produced by:

```yaml
- name: Stop and remove munge.
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - munge
  when: galaxy_extras_config_slurm and supervisor_manage_slurm
```

the undersired effect (wrong evaluation of the complete boolean construct) is only seen when you have at least one of the two variables as false, as true/true seem to evaluate as defined or filled strings, and hence true. Unfortunately, there is little documentation on the ansible site about this. This is solved by using a `|bool` filter after each boolean in the _when_ statement.

This is when running on Ubuntu 14.04 and Ansible 2.1, as installed in bgruening/docker-galaxy-stable. I have tested the suggested changes, and the final outcome is as expected (no Ansible failure and installation according to booleans set). and will submit a PR soon.
